import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const amazonEmber = localFont({
  src: "./fonts/Amazon Ember.ttf",
  variable: "--font-amazon-ember",
  weight: "400 700",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${amazonEmber.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
